### ISSUE TITLE
Support long captions

### ISSUE THREAD

**Issue by evezeyl** [bicarlsen/obsidian_image_caption#11]
Hi,
I am trying to use a long caption.
Then the full length of the caption does not display.  
Any way to cut into several lines (eg \n, <br> ...)? 
or to wrap the caption on several lines ?
Thanks for this already nice addition 
All the best
Eve

**Comment by bicarlsen** [comment]
Thanks for the suggestion. Captions should wrap automatically if they are long. However if you want to force a line break I added an option in version 0.0.12 to insert the caption as HTML instead of text. Thus you should be able to force a line break using the `<br/>` tag.

Please give it a try and let em know if it works.

**Comment by bicarlsen** [comment]
I'll close this issue due to lack of activity. If you experience any other issues, please feel free to open another issue.
